# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: deploy
#   password: password123456789
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#
# development:
#   <<: *default
#   database: thenewspanel_development
#
# test:
#   <<: *default
#   database: thenewspanel
#
# production:
#   <<: *default
#   database: thenewspanel
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: thenewspanel

test:
  <<: *default
  database: thenewspanel
    # db/test.sqlite3

production:
  <<: *default
  database: thenewspanel
    # db/production.sqlite3
