default: 
    adapter: postgresql
    encoding: utf8
    pool: 5
    database: hadhratabassiya
    username: deploy
    password: boomboom0
    host: localhost

development:
    adapter: postgresql
    encoding: utf8
    pool: 5
    database: hadhratabassiya_development
    username: deploy
    password: boomboom0
    host: localhost

test:
  database: hadhratabassiya


production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: hadhratabassiya_production
  pool: 5
  username: <%= ENV['deploy'] %>
  password: <%= ENV['boomboom0'] %>