development:
  adapter: postgresql
  encoding: unicode
  database: hadhratabassiya_development
  pool: 5
  username: deploy
  password: boomboom0
  host: localhost


test:
  database: hadhratabassiya


production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: hadhratabassiya_production
  pool: 5
  username: <%= ENV['deploy'] %>
  password: <%= ENV['boomboom0'] %>