development:
  database: hadhratabassiya
  adapter: postgresql
  username: 'deploy'
  password: 'boomboom0'
  host: localhost
  port: 5432
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  database: hadhratabassiya

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: hadhratabassiya_production
  pool: 5
  username: <%= ENV['deploy'] %>
  password: <%= ENV['boomboom0'] %>
