# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: deploy
  password: password123456789
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: thenewspanel

test:
  <<: *default
  database: thenewspanel
    # db/test.sqlite3

production:
  <<: *default
  database: thenewspanel
    # db/production.sqlite3
