development:
  adapter: postgresql
  encoding: unicode
  database: hadhratabassiya_development
  pool: 5
  username: deploy
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: hadhratabassiya_test
  pool: 5
  username: deploy
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: hadhratabassiya_production
  pool: 5
  username: deploy
  password:


# development:
#   database: hadhratabassiya_development
#   host: localhost
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#   username: deploy
#   password: boomboom0


# test:
#   database: hadhratabassiya


# production:
#   host: localhost
#   adapter: postgresql
#   encoding: utf8
#   database: hadhratabassiya_production
#   pool: 5
#   username: <%= ENV['deploy'] %>
#   password: <%= ENV['boomboom0'] %>